package constant

var AdPartnerParams []string = []string{"sub1", "url", "$fallback_url"}

var AdPartners map[string]bool = map[string]bool{
	"ad.atdmt.com":              true,
	"atdmt.com":                 true,
	"ad.admitad.com":            true,
	"admitad.com":               true,
	"s.afilio.com.br":           true,
	"afilio.com.br":             true,
	"bit.ly":                    true,
	"clickserve.dartsearch.net": true,
	"dartsearch.net":            true,
	"ad.doubleclick.net":        true,
	"doubleclick.net":           true,
	"fg8dgt.com":                true,
	"pixel.everesttech.net":     true,
	"adservice.google.com":      true,
	"google.com.br/aclk":        true,
	"google.com/aclk":           true,
	"analytics.bluekai.com":     true,
	"bluekai.com":               true,
	"xg4ken.com":                true,
	"clickcease.com":            true,
	"linksynergy.com":           true,
	"vzadtrack.xyz":             true,
	"compre.vc":                 true,
	"socialsoul.com.vc":         true,
	"go2cloud.org":              true,
	"redipath.com":              true,
	"lvxtnc.online":             true,
	"ecqyey.shop":               true,
	"jlzmoa.xyz":                true,
	"encurtador.com.br":         true,
	"krxd.net":                  true,
	"s.click.aliexpress.com":    true,
	"lunio.ai":                  true,
	"t.myvisualiq.net":          true,
	"awin1.com":                 true,
	"oferta.vc":                 true,
	"app.link":                  true,
	"clichetrends.com":          true,
	"advertracking.com":         true,
	"trafficguard.ai":           true,
}
