package constant

var SiteTypes = map[string]string{
	"apps.apple.com":                "appstore",
	"play.google.com":               "appstore",
	"business.google.com":           "bizprofile",
	"sites.google.com":              "sitebuilder",
	"blogspot.com":                  "sitebuilder",
	"www.wixsite.com":               "sitebuilder",
	"wixsite.com":                   "sitebuilder",
	"rds.land":                      "sitebuilder",
	"godaddysites.com":              "sitebuilder",
	"weebly.com":                    "sitebuilder",
	"webnode.page":                  "sitebuilder",
	"magazinevoce.com.br":           "sitebuilder",
	"myshopify.com":                 "sitebuilder",
	"soliciteumcontato.com.br":      "sitebuilder",
	"hotmart.com":                   "sitebuilder",
	"go.hotmart.com":                "sitebuilder",
	"udemy.com":                     "sitebuilder",
	"vercel.app":                    "sitebuilder",
	"canva.site":                    "sitebuilder",
	"api.whatsapp.com":              "phone",
	"wa.me":                         "phone",
	"telegram.me":                   "phone",
	"t.me":                          "phone",
	"linktr.ee":                     "socialnetwork",
	"instagram.com":                 "socialnetwork",
	"google.com.br/search":          "searchresult",
	"google.com/search":             "searchresult",
	"instagram.com/accounts/login/": "socialnetwork",
}
